export * from './TemplateHOC';
export * from './Template2HOC'
export * from './LoaderHOC/LoaderHOC';
export * from './RouteHOC';
export * from './SignUpHOC';
export * from './SignInHOC';
export * from './SignOutHOC';
export * from './AuthHOC';
export * from './UploadWorkHOC';